# config/interfaces/http.yaml

# Конфигурация HTTP-сервера и API
http:
  # Основные настройки сервера
  server:
    host: ${HTTP_HOST:0.0.0.0}
    port: ${HTTP_PORT:8000}
    workers: ${WEB_CONCURRENCY:1}  # Количество воркеров (рекомендуется: ядра CPU * 2 + 1)
    worker_class: "uvicorn.workers.UvicornWorker"
    keepalive: 5  # Таймаут keep-alive соединений (сек)
    timeout: 120  # Таймаут обработки запроса (сек)
    backlog: 2048  # Размер очереди входящих соединений
    limit_concurrency: 1000  # Максимальное количество одновременных запросов
    limit_max_requests: 10000  # Максимальное количество запросов на воркер перед перезапуском

  # Настройки API
  api:
    # Версионирование
    version: "1.0"
    v1_prefix: "/api/v1"
    version_header: "X-API-Version"
    deprecated_header: "X-API-Deprecated"
    
    # Документация
    docs:
      enabled: true
      url: "/docs"
      redoc_url: "/redoc"
      openapi_url: "/openapi.json"
      title: "NeuroGraph OS API"
      description: "Документация по REST API NeuroGraph OS"
      contact:
        name: "Поддержка"
        email: "support@neurograph.ai"
      license:
        name: "Proprietary"
        url: "https://neurograph.ai/license"

  # Безопасность
  security:
    # CORS
    cors:
      enabled: true
      allow_origins: ${CORS_ALLOW_ORIGINS:["*"]}
      allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
      allow_headers: ["*"]
      allow_credentials: true
      expose_headers: ["X-Total-Count", "X-Request-ID"]
      max_age: 600  # Кэширование preflight запросов (сек)

    # Защита от перегрузки
    rate_limiting:
      enabled: true
      storage: "redis"  # redis | memory
      strategy: "fixed-window"  # fixed-window | sliding-window
      rate: "100/minute"  # Лимит по умолчанию
      headers:
        enabled: true
        limit: "X-RateLimit-Limit"
        remaining: "X-RateLimit-Remaining"
        reset: "X-RateLimit-Reset"

  # Промежуточное ПО
  middleware:
    request_id:
      enabled: true
      header: "X-Request-ID"
    logging:
      enabled: true
      format: '${time} | ${status} | ${method} ${path} | ${ip} | ${latency}'
    gzip:
      enabled: true
      minimum_size: 500  # Минимальный размер ответа для сжатия (байт)
    https_redirect:
      enabled: ${FORCE_HTTPS:false}
    trusted_hosts:
      enabled: true
      allowed_hosts: ${ALLOWED_HOSTS:["*"]}

  # Настройки запросов
  requests:
    max_body_size: "10MB"  # Максимальный размер тела запроса
    timeout: 30  # Таймаут обработки запроса (сек)
    keep_alive: 5  # Таймаут keep-alive (сек)
    client_max_size: "100MB"  # Максимальный размер загружаемых файлов

  # WebSockets
  websockets:
    enabled: true
    path: "/ws"
    ping_interval: 20  # Интервал пингов (сек)
    ping_timeout: 30  # Таймаут ожидания пинга (сек)
    max_message_size: "1MB"  # Максимальный размер сообщения
    queue_size: 100  # Размер очереди сообщений на соединение

  # Мониторинг и метрики
  metrics:
    enabled: true
    path: "/metrics"
    include_status_codes: "100-599"
    buckets: [0.01, 0.05, 0.1, 0.5, 1, 2.5, 5, 10]
    namespace: "neurograph_http"

  # Отладка
  debug:
    request_logging: ${DEBUG:false}
    error_details: ${DEBUG:false}
    traceback: ${DEBUG:true}
    slow_requests:  # Логирование медленных запросов
      enabled: true
      threshold: 1.0  # Порог медленного запроса (сек)

  # Кастомизация ответов
  responses:
    default_headers:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
    error_format:  # Формат ошибок API
      error: true
      message: ""
      code: null
      details: null