# config/interfaces/http.yaml

server:
  host: "0.0.0.0"
  port: ${API_PORT:8000}

api:
  v1_prefix: "/api/v1"
  docs_url: "/docs"
  redoc_url: "/redoc"
  project_name: "NeuroGraph OS"
  version: "1.1.0"