# config/infrastructure/persistence.yaml

# Конфигурация постоянных хранилищ данных
persistence:
  # Настройки PostgreSQL
  postgresql:
    # Параметры подключения
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    database: ${POSTGRES_DB:neurograph}
    ssl: ${POSTGRES_SSL:false}
    application_name: "neurograph_app"
    
    # Пул соединений
    pool:
      size: ${DB_POOL_SIZE:10}
      max_overflow: ${DB_MAX_OVERFLOW:20}
      timeout: ${DB_POOL_TIMEOUT:30}  # в секундах
      recycle: ${DB_POOL_RECYCLE:3600}  # пересоздавать соединения раз в час
      pre_ping: ${DB_PRE_PING:true}  # проверять соединение перед использованием
      
    # Настройки производительности
    performance:
      statement_timeout: ${DB_STATEMENT_TIMEOUT:30000}  # мс
      idle_in_transaction_session_timeout: ${DB_IDLE_TIMEOUT:30000}  # мс
      connect_timeout: ${DB_CONNECT_TIMEOUT:5}  # сек
      keepalives_idle: ${DB_KEEPALIVE_IDLE:30}  # сек
      keepalives_interval: ${DB_KEEPALIVE_INTERVAL:10}  # сек
      keepalives_count: ${DB_KEEPALIVE_COUNT:5}
      
    # Логирование
    echo: ${SQL_ECHO:false}
    echo_pool: ${SQL_ECHO_POOL:false}
    hide_parameters: ${HIDE_SQL_PARAMETERS:true}
    
    # Миграции
    migrations:
      enabled: true
      table: "alembic_version"
      location: "alembic"
      version_locations: "alembic/versions"
      include_schemas: true
      compare_server_default: true
      compare_type: true

  # Настройки Redis
  redis:
    # Параметры подключения
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    db: ${REDIS_DB:0}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    
    # Пул соединений
    pool:
      minsize: ${REDIS_POOL_MINSIZE:1}
      maxsize: ${REDIS_POOL_MAXSIZE:10}
      timeout: ${REDIS_POOL_TIMEOUT:5}  # сек
      max_connections: ${REDIS_MAX_CONNECTIONS:20}
      
    # Настройки производительности
    socket_timeout: ${REDIS_SOCKET_TIMEOUT:5.0}  # сек
    socket_connect_timeout: ${REDIS_CONNECT_TIMEOUT:5.0}  # сек
    retry_on_timeout: ${REDIS_RETRY_ON_TIMEOUT:true}
    health_check_interval: ${REDIS_HEALTH_CHECK:30}  # сек
    
    # Кластерный режим
    cluster_mode: ${REDIS_CLUSTER:false}
    startup_nodes: ${REDIS_STARTUP_NODES:[]}
    
    # Sentinel режим
    sentinel:
      enabled: ${REDIS_SENTINEL:false}
      service_name: ${REDIS_SENTINEL_SERVICE:mymaster}
      sockets: ${REDIS_SENTINEL_SOCKETS:[]}

  # Настройки кэширования
  cache:
    default_ttl: 300  # сек
    key_prefix: "neurograph:cache:"
    compression: true
    compression_level: 3  # 1-9
    
    # Распределенный кэш
    distributed:
      enabled: true
      strategy: "consistent_hashing"  # consistent_hashing | sharding
      replication: false
      
    # Локальный кэш
    local:
      enabled: true
      max_size: 10000
      ttl: 60  # сек

  # Резервное копирование
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Каждый день в 2:00
    retention_days: 30
    s3_bucket: ${BACKUP_S3_BUCKET:}
    local_path: "/var/backups/neurograph"
    encryption_key: ${BACKUP_ENCRYPTION_KEY:}