# config/infrastructure/persistence.yaml

# Настройки для постоянных хранилищ данных

postgresql:
  host: ${POSTGRES_HOST:db}
  port: ${POSTGRES_PORT:5432}
  user: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:password} # Значение из docker-compose.yaml
  database: ${POSTGRES_DB:neurograph}
  pool_size: 10
  max_overflow: 20

redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:0}
  password: ${REDIS_PASSWORD:} # По умолчанию пароля нет
  pool_size: 10
  max_overflow: 20