# NeuroGraph OS - WebSocket Configuration

websocket:
  # Server settings
  server:
    host: ${WEBSOCKET_HOST:0.0.0.0}
    port: ${WEBSOCKET_PORT:8000}
    path: /ws
    
  # Connection settings
  connection:
    max_connections: 1000
    heartbeat_interval: 30  # seconds
    connection_timeout: 300  # seconds
    max_message_size: 1048576  # 1MB
    
  # Authentication
  authentication:
    enabled: false
    token_header: "Authorization"
    token_prefix: "Bearer"
    
  # Message handling
  messaging:
    queue_size: 1000
    enable_compression: true
    message_retention: 100  # Keep last N messages per connection
    
  # Topics and subscriptions
  topics:
    max_subscriptions_per_connection: 50
    default_topics:
      - system
      - tokens
      - graph
      - experience
      
  # Rate limiting
  rate_limiting:
    enabled: true
    messages_per_minute: 60
    burst_size: 10
    
  # Monitoring
  monitoring:
    enabled: true
    metrics_interval: 60  # seconds
    log_connections: true
    log_messages: false  # Set to true for debugging
    
  # CORS
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
    allow_credentials: true
    allow_methods:
      - GET
      - POST
      - OPTIONS
    allow_headers:
      - "*"

# Event publishing
event_publisher:
  enabled: true
  
  # Event types to publish via WebSocket
  publish_events:
    - token.created
    - token.updated
    - token.deleted
    - graph.connected
    - graph.disconnected
    - experience.recorded
    
  # Batch publishing
  batch:
    enabled: true
    batch_size: 10
    batch_interval: 1000  # milliseconds