# Event Bus Configuration
# This file contains the default configuration for the NeuroGraph OS Event System

default:
  # General settings
  max_queue_size: 10000  # Maximum number of events in the queue
  worker_count: 4        # Number of worker tasks for processing events
  
  # Performance settings
  batch_size: 100       # Number of events to process in a single batch
  max_retries: 3        # Maximum number of retries for failed event processing
  
  # Monitoring and logging
  enable_metrics: true  # Enable collection of performance metrics
  log_events: false     # Log all events (warning: can be verbose)
  log_level: "INFO"     # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  
  # Timeout settings (in seconds)
  publish_timeout: 5.0   # Timeout for publishing events
  shutdown_timeout: 10.0 # Timeout for graceful shutdown

# Development-specific settings
development:
  <<: *default
  log_events: true
  log_level: "DEBUG"

# Production settings
production:
  <<: *default
  worker_count: 8
  log_events: false
  log_level: "WARNING"
