# Конфигурация шины событий
# Этот файл содержит настройки по умолчанию для системы событий NeuroGraph OS

default:
  # Основные настройки
  max_queue_size: 10000  # Максимальное количество событий в очереди
  worker_count: 4        # Количество воркеров для обработки событий
  
  # Настройки производительности
  batch_size: 100       # Количество событий для пакетной обработки
  max_retries: 3        # Максимальное количество повторов при ошибке обработки
  
  # Мониторинг и логирование
  enable_metrics: true  # Включить сбор метрик производительности
  log_events: false     # Логировать все события (может быть много записей)
  log_level: "INFO"     # Уровень логирования (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  
  # Таймауты (в секундах)
  publish_timeout: 5.0   # Таймаут публикации событий
  shutdown_timeout: 10.0 # Таймаут корректного завершения работы

# Настройки для разработки
development:
  <<: *default
  log_events: true
  log_level: "DEBUG"

# Настройки для продакшена
production:
  <<: *default
  worker_count: 8
  log_events: false
  log_level: "WARNING"
