event_bus:
  max_queue_size: 10000
  enable_metrics: true
  log_events: false

event_types:
  token:
    enabled: true
    default_priority: "NORMAL"
  graph:
    enabled: true
    default_priority: "NORMAL"
  dna:
    enabled: true
    default_priority: "HIGH"
  experience:
    enabled: true
    default_priority: "LOW"

integrations:
  experience_stream:
    enabled: true
    record_categories:
      - "token"
      - "graph"
      - "evolution"
