# config/core/spatial.yaml

# Настройки для пространственных компонентов (CoordinateSystem, SparseGrid и т.д.)
spatial:
  coordinate_system:
    enable_validation: true       # Включить валидацию координат при размещении токенов
    max_search_results: 1000      # Максимальное количество результатов в пространственных запросах
    enable_statistics: true       # Включить сбор статистики по операциям
    # Если true, система координат будет пытаться автоматически переиндексировать
    # уровни при изменениях CDNA/ADNA масштабов. По умолчанию выключено — чтобы
    # избежать рискованных автоматических операций в проде.
    enable_auto_reindex: false

  sparse_grid:
    precision: 2                  # Количество знаков после запятой для округления координат