# config/core/spatial.yaml

# Конфигурация пространственной подсистемы
spatial:
  # Основные настройки
  environment: "development"  # development/staging/production
  log_level: "INFO"           # Уровень логирования
  enabled: true              # Включение/отключение подсистемы

  # Система координат
  coordinate_system:
    type: "cartesian"        # cartesian | polar | spherical
    dimensions: 3            # Количество измерений (2 или 3)
    precision: 6             # Точность вычислений (знаков после запятой)
    auto_normalize: true     # Автоматическая нормализация координат
    bounds_check: true       # Проверка границ координатного пространства
    
    # Ограничения координат
    bounds:
      min: [-1000.0, -1000.0, -1000.0]  # Минимальные значения по осям
      max: [1000.0, 1000.0, 1000.0]     # Максимальные значения по осям
      wrap_around: false     # Заворачивание координат при выходе за границы

  # Пространственные запросы
  queries:
    default_max_results: 1000  # Максимальное количество результатов по умолчанию
    timeout_ms: 1000          # Таймаут выполнения запроса (мс)
    cache_enabled: true       # Кэширование результатов запросов
    cache_ttl: 300            # Время жизни кэша (сек)
    
    # Оптимизация запросов
    optimization:
      use_spatial_index: true  # Использовать пространственные индексы
      batch_size: 1000         # Размер пакета для пакетных запросов
      parallel_processing: true # Параллельная обработка запросов

  # Пространственные отношения
  relations:
    # Точность сравнения координат
    epsilon: 1.0e-6           # Погрешность при сравнении координат
    
    # Настройки для различных операций
    contains:
      boundary_policy: "include"  # include | exclude
    intersects:
      boundary_policy: "include"
    distance:
      algorithm: "euclidean"  # euclidean | manhattan | haversine
      unit: "meters"          # Единицы измерения расстояния

  # Пространственные преобразования
  transformations:
    # Масштабирование
    scale:
      auto_detect: true      # Автоматическое определение необходимости масштабирования
      reference_point: [0, 0, 0]  # Точка отсчета для масштабирования
      
    # Поворот
    rotation:
      order: "xyz"           # Порок осей вращения
      degrees: true          # true - градусы, false - радианы
      
    # Перенос
    translation:
      auto_offset: true      # Автоматическое смещение координат

  # Интеграция с другими подсистемами
  integration:
    # Интеграция с Grid
    grid:
      auto_sync: true        # Автоматическая синхронизация с Grid
      sync_interval: 60      # Интервал синхронизации (сек)
      
    # Интеграция с Graph
    graph:
      spatial_indexing: true  # Индексировать пространственные данные графа
      max_neighbors: 50      # Максимальное количество соседей для пространственного поиска

  # Мониторинг и метрики
  monitoring:
    enabled: true
    metrics_prefix: "spatial"
    collect_interval: 60     # Интервал сбора метрик (сек)
    track:
      query_timings: true    # Время выполнения запросов
      memory_usage: true     # Использование памяти
      cache_hit_ratio: true  # Эффективность кэширования
      transformation_stats: true  # Статистика преобразований

  # Настройки отладки
  debug:
    log_operations: false    # Логировать пространственные операции
    validate_input: true     # Валидация входных данных
    dump_on_error: true      # Сохранять дамп при ошибке
    profile_performance: false # Профилирование производительности