# config/core/token.yaml
token:
  # Базовые настройки токена
  binary_format: "<24h I H f H I"  # Формат упаковки/распаковки
  binary_size: 64                  # Размер токена в байтах
  absent_value: 127                # Значение для отсутствующих координат
  max_levels: 8                    # Максимальное количество уровней
  coordinates_per_level: 3         # Количество осей на уровень (x,y,z)

  # Настройки фабрики токенов
  factory:
    defaults:
      weight: 0.0                  # Вес по умолчанию
      flags: 0                     # Флаги по умолчанию
      auto_timestamp: true         # Автоматическая установка временной метки
      precision: 2                 # Точность округления координат

    # Форматы специализированных токенов
    formats:
      # Токен опыта (для обучения с подкреплением)
      experience:
        state_level: 0             # Уровень для состояния (s_t)
        action_level: 1            # Уровень для действия (a_t)
        next_state_level: 2        # Уровень для следующего состояния (s_t+1)
        done_flag_bit: 0           # Бит для флага завершения эпизода
        reward_clip_min: -1.0      # Минимальное значение награды
        reward_clip_max: 1.0       # Максимальное значение награды

      # Токен состояния (для входных данных)
      state:
        level: 0                   # Уровень для хранения состояния
        vector_encoding: "direct"  # Способ кодирования вектора

      # Токен действия (для выходных данных)
      action:
        level: 1                   # Уровень для хранения действия
        vector_encoding: "direct"  # Способ кодирования вектора

  # Валидация токенов
  validation:
    check_coordinate_bounds: true  # Проверять границы координат
    min_coord: -1.0               # Минимальное значение координаты
    max_coord: 1.0                # Максимальное значение координаты
    max_vector_dim: 24            # Максимальная размерность вектора