# config/application/token_service.yaml
# Настройки для сервиса управления токенами (TokenService)

# Общие настройки сервиса
service:
  # Включен ли сервис. Если false, вызовы к нему могут быть заблокированы.
  enabled: true
  # Имя класса для DI-контейнера или фабрики сервисов.
  class: "TokenService"

# Параметры по умолчанию для создания токенов через сервис.
# Эти значения могут быть переопределены при вызове метода.
creation_defaults:
  # Уровень в пространственной сетке, на котором токен создается по умолчанию.
  level: 0
  # Вес, присваиваемый новому токену, если не указан другой.
  weight: 0.5
  # Начальные флаги для нового токена.
  flags: 0

# Настройки поведения, связанные с другими компонентами ядра.
behavior:
  # Следует ли автоматически создавать пространственные связи при добавлении токена.
  auto_connect_spatial: true
  # Следует ли автоматически создавать временные связи.
  auto_connect_temporal: true