# TokenGraph Configuration v1.0
# Configuration for graph-based knowledge representation and evolution

token_graph:
  version: "1.0.0"
  
  # ============================================================================
  # TOPOLOGY CONFIGURATION
  # ============================================================================
  topology:
    max_nodes: 1000000
    max_edges: 10000000
    allow_self_loops: false
    allow_multi_edges: false
    
    initial_structure:
      create_random: false
      initial_nodes: 0
      initial_connections: 0
  
  # ============================================================================
  # EVOLUTION CONFIGURATION
  # ============================================================================
  evolution:
    mutation_rate: 0.01
    crossover_rate: 0.05
    selection_pressure: 0.7
    fitness_threshold: 0.3
    max_mutations_per_cycle: 1000
    
    mutation_weights:
      ADD_CONNECTION: 0.2
      REMOVE_CONNECTION: 0.1
      MODIFY_WEIGHT: 0.4
      CHANGE_TYPE: 0.2
      REVERSE_DIRECTION: 0.1
    
    schedule:
      mutation_interval: 100
      selection_interval: 500
      crossover_interval: 1000
  
  # ============================================================================
  # WEIGHT CONFIGURATION
  # ============================================================================
  weights:
    initial_weight: 0.5
    decay_rate: 0.99
    strengthen_amount: 0.1
    min_weight: 0.01
    max_weight: 1.0
    
    decay_schedule:
      enabled: true
      interval_seconds: 3600
      rate_per_interval: 0.95
  
  # ============================================================================
  # CONNECTION TYPE CONFIGURATION
  # ============================================================================
  connection_types:
    allowed_types: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    default_type: 1  # ASSOCIATION
    
    type_configs:
      ASSOCIATION:
        default_weight: 0.5
        bidirectional_default: false
      HIERARCHY:
        default_weight: 0.8
        bidirectional_default: false
      CAUSALITY:
        default_weight: 0.7
        bidirectional_default: false
      SIMILARITY:
        default_weight: 0.6
        bidirectional_default: true
      PROXIMITY:
        default_weight: 0.4
        bidirectional_default: true
  
  # ============================================================================
  # CDNA INTEGRATION
  # ============================================================================
  cdna_integration:
    validate_all_operations: true
    enforce_degree_limit: true
    enforce_distance_limit: false
    
    rules:
      max_degree: 1000
      connection_distance_range: [0.0, 1000.0]
      min_weight: 0.01
      max_weight: 1.0
      allow_self_loops: false
      allow_multi_edges: false
  
  # ============================================================================
  # EXPERIENCE INTEGRATION
  # ============================================================================
  experience_integration:
    record_all_operations: true
    calculate_rewards: true
    track_fitness: true
    
    recorded_events:
      - token_added
      - token_removed
      - connection_created
      - connection_removed
      - mutation_applied
      - crossover_applied
      - selection_applied
    
    rewards:
      token_added: 0.1
      connection_created: 0.5
      bridge_connection: 0.8
      hub_creation: 0.6
      over_connection: -0.2
      weak_connection: -0.1
  
  # ============================================================================
  # STATISTICS & MONITORING
  # ============================================================================
  statistics:
    enabled: true
    calculation_interval: 100
    
    tracked_metrics:
      - node_count
      - edge_count
      - density
      - average_degree
      - connected_components
      - hub_nodes
      - fitness
      - mutation_rate_actual
    
    history:
      max_snapshots: 1000
      save_interval_seconds: 300
  
  # ============================================================================
  # MAINTENANCE & OPTIMIZATION
  # ============================================================================
  maintenance:
    enabled: true
    
    schedule:
      prune_interval_seconds: 3600
      compact_interval_seconds: 7200
      stats_interval_seconds: 300
    
    pruning:
      weight_threshold: 0.02
      inactivity_threshold_seconds: 86400
      remove_orphaned_nodes: true
    
    compaction:
      target_density: 0.1
      min_size_for_compaction: 10000
  
  # ============================================================================
  # PERSISTENCE
  # ============================================================================
  persistence:
    enabled: true
    backend: "file"
    
    file:
      snapshot_dir: "data/graphs/snapshots"
      format: "json"
      interval_seconds: 600
      max_snapshots: 10
    
    postgresql:
      host: "localhost"
      port: 5432
      database: "neurograph"
      table_prefix: "token_graph_"
    
    redis:
      host: "localhost"
      port: 6379
      db: 0
      key_prefix: "token_graph:"
  
  # ============================================================================
  # PERFORMANCE
  # ============================================================================
  performance:
    enabled: true
    
    indexing:
      spatial_index: true
      type_index: true
      rebuild_interval: 1000
    
    caching:
      cache_subgraphs: true
      cache_statistics: true
      cache_ttl: 300
      max_cache_size: 1000
    
    batching:
      enabled: true
      batch_size: 100
  
  # ============================================================================
  # LOGGING & DEBUGGING
  # ============================================================================
  logging:
    level: "INFO"
    log_operations: false
    log_evolution: true
    log_statistics: false
    file: "logs/token_graph.log"
    format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"
  
  # ============================================================================
  # ADVANCED FEATURES
  # ============================================================================
  advanced:
    multi_layer:
      enabled: false
      layers: ["semantic", "spatial", "temporal"]
    
    adaptive_topology:
      enabled: false
      adaptation_rate: 0.01
    
    parallel:
      enabled: false
      num_workers: 4
    
    communities:
      enabled: false
      algorithm: "louvain"
      min_community_size: 5
