# config/core/token.yaml

# Настройки, связанные с сущностью "Токен" и ее производными.
token:
  factory:
    # Значения по умолчанию для всех создаваемых токенов
    defaults:
      weight: 0.0
      flags: 0
      auto_timestamp: true

    # Специализация для "токенов опыта" (Reinforcement Learning)
    # Определяет, как данные опыта упаковываются в уровни токена.
    experience_format:
      # Уровень для вектора состояния (s_t)
      state_level: 0
      # Уровень для вектора действия (a_t)
      action_level: 1
      # Уровень для вектора следующего состояния (s_t+1)
      next_state_level: 2
      # Номер бита в поле `flags` для обозначения конца эпизода (done)
      done_flag_bit: 0