# config/environments/development.yaml

# Конфигурация окружения разработки
app:
  # Основные настройки приложения
  env: "development"
  debug: true
  log_level: "DEBUG"
  project_name: "NeuroGraph OS"
  timezone: "UTC"
  locale: "en_US.UTF-8"
  
  # Безопасность
  secret_key: "dev-secret-key"  # Переопределить через SECRET_KEY в продакшене
  password_salt_rounds: 10
  session_lifetime: 86400  # 24 часа в секундах

# Настройки сервера
server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 1
  worker_class: "uvicorn.workers.UvicornWorker"
  keepalive: 5
  timeout: 120
  log_level: "debug"
  access_log: true

# Настройки CORS
cors:
  enabled: true
  allow_origins: ["*"]  # В продакшене указать конкретные домены
  allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  allow_headers: ["*"]
  allow_credentials: true
  expose_headers: []
  max_age: 600

# Настройки базы данных
database:
  # Основные параметры
  url: "postgresql://user:password@localhost:5432/neurograph_dev"
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  pool_pre_ping: true
  echo: true
  echo_pool: false
  
  # Миграции
  migrations_enabled: true
  migrations_path: "alembic"
  migrations_table: "alembic_version"

# Кэширование
cache:
  enabled: true
  backend: "redis"  # redis | memcached | memory
  ttl: 300  # Время жизни кэша по умолчанию (сек)
  redis:
    url: "redis://localhost:6379/0"
    socket_timeout: 5.0
    socket_connect_timeout: 5.0
    retry_on_timeout: true

# Логирование
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/development.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  rotation: "1 day"

# Отладка и профилирование
debug_toolbar:
  enabled: true
  intercept_redirects: false
  panels: [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
  ]

# Настройки для разработки
development:
  # Автоматическая перезагрузка при изменениях
  reload_dirs: ["app", "config"]
  reload_delay: 0.25  # Задержка перед перезагрузкой (сек)
  
  # Профилирование
  profile: false
  profile_dir: "profiles"
  
  # Документация API
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"

# Настройки для тестирования
testing:
  database_url: "postgresql://user:password@localhost:5432/neurograph_test"
  create_tables: true
  drop_tables: true

# Внешние сервисы (заглушки для разработки)
external_services:
  email:
    enabled: false
    backend: "console"  # console | smtp | sendgrid
  storage:
    backend: "filesystem"  # filesystem | s3 | gcs
    path: "./storage"